# A file's bytes as a C array (cmake -DIN=file -DOUT=header -DNAME=identifier -P embed.cmake): the hardware renderer's
# compiled shaders (port/CMakeLists.txt, port/runtime/render_gpu.c) go into the binary, which stays one file. Aligned to
# 16 bytes: SPIR-V is read as 32-bit words.
file(READ "${IN}" hex HEX)
string(LENGTH "${hex}" len)
math(EXPR size "${len} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
string(REGEX REPLACE "((0x..,){16})" "\\1\n    " bytes "${bytes}")
file(WRITE "${OUT}.tmp" "/* Generated by port/cmake/embed.cmake from ${IN}: do not edit. */\n"
     "static const unsigned char ${NAME}[${size}] __attribute__((aligned(16))) = {\n    ${bytes}\n};\n")
file(COPY_FILE "${OUT}.tmp" "${OUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUT}.tmp")
