# The build's version stamp (docs/PORT.md "Crash report"): `git describe` over the release tags (vX.Y.Z, as the
# packages are named), "dev-<commit>" before any, "-dirty" with uncommitted changes, and the commit's hash;
# PSXSTACK_VERSION (the release's tag) wins over git describe. Run at every build (cmake -P, from a custom command of
# the port's and the launcher's CMakeLists), it rewrites OUT only when the text changed, so a build with nothing new
# relinks nothing. ROOT is the repository the build is named after: a game repo passes its own.
#
#   cmake -DROOT=<repo> -DOUT=<file.c> [-DPREFIX=port] -P cmake/version.cmake
#
# OUT defines `const char <PREFIX>_version[]` and `const char <PREFIX>_commit[]`.
if(NOT ROOT OR NOT OUT)
    message(FATAL_ERROR "version.cmake: -DROOT=<repo> -DOUT=<file.c> are required")
endif()
if(NOT PREFIX)
    set(PREFIX "port")
endif()
set(version "$ENV{PSXSTACK_VERSION}")
set(commit "unknown")
find_package(Git QUIET)
if(GIT_FOUND)
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${ROOT}" rev-parse HEAD
                    OUTPUT_VARIABLE c OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE r)
    if(r EQUAL 0 AND c)
        set(commit "${c}")
    endif()
    if(NOT version)
        execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${ROOT}" describe --tags --match "v[0-9]*.[0-9]*.[0-9]*"
                                --always --dirty
                        OUTPUT_VARIABLE d OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET RESULT_VARIABLE r)
        if(r EQUAL 0 AND d)
            if(d MATCHES "^v")
                string(SUBSTRING "${d}" 1 -1 version)
            else()
                set(version "dev-${d}")
            endif()
        endif()
    endif()
endif()
if(NOT version)
    set(version "unknown")
endif()
string(REGEX REPLACE "^v" "" version "${version}")
set(text "/* Generated by cmake/version.cmake at build time; do not edit. */\n")
string(APPEND text "const char ${PREFIX}_version[] = \"${version}\";\n")
string(APPEND text "const char ${PREFIX}_commit[] = \"${commit}\";\n")
set(old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" old)
endif()
if(NOT old STREQUAL text)
    file(WRITE "${OUT}" "${text}")
endif()
